# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Human Evolution Mobile.xcodeproj")
    match(type: "appstore")
    gym(
      export_method: "app-store",
      # project: "YourAppName.xcodeproj",
      workspace: "Human Evolution Mobile.xcworkspace", # do either the project or workspace line - workspace if you are using pods, project if not
      scheme: "Human Evolution Mobile",
    )
    upload_to_testflight
  end
end

# default_platform(:ios)
#
# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
#     build_app(workspace: "Human Evolution Mobile.xcworkspace", scheme: "Human Evolution Mobile")
#     upload_to_testflight
#   end
# end
